# Generated by Django 6.1 on 2026-09-03 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_faculty_name_faculty_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.faculty'),
        ),
    ]
